name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: 24.x

      - run: npm ci

      - run: npm test

  Percy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - run: npx @percy/cli snapshot src/
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
